Repository wsvvrijheid/samenvvv, pull requests merged in 2021-11, with the labels that each got.

#68 Feat/contact
  .gitignore
  next.config.js
  pages/contact.tsx
  public/locales/en/common.json
  public/locales/nl/common.json
  public/locales/tr/common.json
  src/components/FormItem/index.tsx
  src/components/index.ts
  src/utils/routes/index.ts
  yarn.lock
Labels: page

#77 FormItem & Contact Page
  next.config.js
  package.json
  pages/contact.tsx
  public/images/bg-wave.svg
  public/locales/en/common.json
  public/locales/nl/common.json
  public/locales/tr/common.json
  src/components/ContactForm/index.tsx
  src/components/FormItem/index.tsx
  src/components/Layout/index.tsx
  src/components/SocialButtons/index.tsx
  src/components/index.ts
  src/utils/routes/index.ts
  src/views/SubView/index.tsx
  yarn.lock
Labels: enhancement

#89 Post Maker Seo & Design
  pages/[...slug].tsx
  pages/index.tsx
  src/components/HeaderTop/index.tsx
  src/components/Layout/index.tsx
  src/components/PostContainer/index.tsx
  src/components/TweetWidget/index.tsx
  src/lib/getData/getApplication.ts
  src/lib/getData/getCompetition.ts
  src/lib/getData/getHashtag.ts
  src/lib/getData/getHashtagPost.ts
  src/lib/getData/getHashtagPosts.ts
  src/lib/getData/getPage.ts
  src/lib/getData/getSubpage.ts
  src/lib/index.ts
  src/store/post-share.ts
  src/views/HashtagPostView/index.tsx
  src/views/HashtagView/index.tsx
  src/views/index.ts
  types/hashtag-post.d.ts
Labels: bug, design
