Repository wsvvrijheid/samenvvv, pull requests merged in 2021-12, with the labels that each got.

#91 tweet share button intent
  src/components/MentionList/index.tsx
  src/components/PostContainer/index.tsx
  src/components/TrendList/index.tsx
  src/store/post-share.ts
  src/views/HashtagPostView/index.tsx
Labels: enhancement

#94 Mention Search
  public/locales/en/common.json
  public/locales/nl/common.json
  public/locales/tr/common.json
  src/components/MentionList/index.tsx
  src/components/MentionListItem/index.tsx
  src/components/MentionSearch/index.tsx
  src/components/PostContainer/index.tsx
  src/components/Skeletons/MentionListSkeleton.tsx
  src/components/TagList/index.tsx
  src/components/TrendList/index.tsx
  src/components/TweetWidget/index.tsx
  src/components/index.ts
  src/lib/getData/getMentionList.ts
  src/lib/getData/lookupTwitterUsers.ts
  src/lib/index.ts
  src/store/post-share.ts
  src/utils/formatNumber/index.ts
  src/utils/index.ts
  src/views/HashtagPostView/index.tsx
Labels: bug, design

#98 Animated Box
  package.json
  pages/examples/animations.tsx
  src/components/AnimatedBox/index.tsx
  src/components/MotionBox/index.tsx
  src/components/index.ts
  yarn.lock
Labels: enhancement, component

#93 About Us
  next.config.js
  package.json
  pages/contact.tsx
  pages/over-ons.tsx
  public/images/about-us.jpeg
  public/locales/tr/common.json
  src/components/AnimatedBox/index.tsx
  src/components/MotionBox/index.tsx
  src/data/about-us.json
  src/views/SubView/index.tsx
Labels: page

#107 Seo Patch
  next-seo.config.json
  package.json
  pages/[...slug].tsx
  pages/_app.tsx
  pages/contact.tsx
  pages/index.tsx
  pages/over-ons.tsx
  public/images/seo-default.jpeg
  src/components/Card/index.tsx
  src/components/Layout/index.tsx
  src/components/PostArchive/index.tsx
  src/components/PostContainer/index.tsx
  src/hooks/useItemLink/index.ts
  src/utils/getDefaultSeo/index.ts
  src/utils/getItemLink/index.ts
  src/utils/getItemLink/index.tsx
  src/utils/getPageSeo/index.ts
  src/utils/index.ts
  src/views/ApplicationView/index.tsx
  src/views/CompetitionView/index.tsx
  src/views/HashtagPostView/index.tsx
  src/views/MainCompetitionsView/index.tsx
  src/views/MainHashtagsView/index.tsx
  src/views/MainView/index.tsx
  src/views/SubView/index.tsx
Labels: enhancement

#123 Remove Saved Mentions
  public/locales/en/common.json
  public/locales/nl/common.json
  public/locales/tr/common.json
  src/components/MentionList/index.tsx
  src/components/MentionListItem/index.tsx
  src/store/post-share.ts
Labels: enhancement

#137 Feat/post help tour
  package.json
  pages/[...slug].tsx
  public/locales/en/common.json
  public/locales/nl/common.json
  public/locales/tr/common.json
  src/components/MentionList/index.tsx
  src/components/MentionSearch/index.tsx
  src/components/PostContainer/index.tsx
  src/components/TrendListTabs/index.tsx
  src/utils/getSteps/index.ts
  src/utils/index.ts
  src/views/HashtagPostView/index.tsx
  yarn.lock
Labels: enhancement, component

#145 Blog
  pages/blog/[slug].tsx
  pages/blog/index.tsx
  src/components/BlogCard/index.tsx
  src/components/Layout/index.tsx
  src/components/MentionList/index.tsx
  src/components/index.ts
  src/hooks/index.ts
  src/hooks/useLocaleTimeFormat/index.ts
  src/lib/getData/getBlogPaths.ts
  src/lib/getData/getBlogPost.ts
  src/lib/getData/getBlogPosts.ts
  src/lib/index.ts
  src/lib/mutations/decreasePostLike.ts
  src/lib/mutations/increasePostLike.ts
  src/lib/mutations/increasePostView.ts
  src/store/blog.ts
  src/store/index.ts
  src/store/store.ts
  src/utils/getReadingTime/index.ts
  src/utils/index.ts
  types/hashtag-post.d.ts
  types/post.d.ts
  types/subpage.d.ts
  types/user-permission-role.d.ts
  yarn.lock
Labels: enhancement, page

#148 Homepage Hashtags
  pages/examples/slider.tsx
  pages/index.tsx
  public/locales/en/common.json
  public/locales/nl/common.json
  public/locales/tr/common.json
  src/components/Card/index.tsx
  src/components/CardIcon/index.tsx
  src/components/HeaderNavItem/index.tsx
  src/components/MentionListItem/index.tsx
  src/components/SliderHero/index.tsx
  src/components/SubpageSidebarTabs/index.tsx
  src/components/TrendList/index.tsx
  src/components/index.ts
  src/lib/getData/getHashtags.ts
  src/lib/getData/getSubpage.ts
  src/lib/getLocalizedSlugs.ts
  src/lib/index.ts
  types/common.d.ts
Labels: enhancement

#146 Sort MainPage items descending by date
  src/lib/getData/getPage.ts
Labels: bug

#149 Hashtag Archive
  package.json
  src/components/PostArchive/index.tsx
  src/components/ShareButtons/index.tsx
  src/components/Slider/index.tsx
  src/lib/getData/getHashtagPost.ts
  src/views/HashtagPostView/index.tsx
  yarn.lock
Labels: bug

#156 Blog Empty Page
  pages/blog/index.tsx
  public/images/no-blog.svg
  src/components/BlogCard/index.tsx
Labels: invalid

#153 Subpage view count and pagination links
  src/lib/getData/getSubpage.ts
  src/lib/index.ts
  src/lib/mutations/increaseSubpageView.ts
  src/store/index.ts
  src/store/store.ts
  src/store/subpage.ts
  src/views/SubView/index.tsx
Labels: bug, enhancement

#158 footer is renewed
  public/locales/en/common.json
  public/locales/nl/common.json
  public/locales/tr/common.json
  src/components/Footer/index.tsx
  src/components/FooterNav/index.tsx
  src/utils/routes/index.ts
Labels: design

#157 Hashtag Timeline
  next.config.js
  public/images/tweet-widget.svg
  public/locales/en/common.json
  public/locales/nl/common.json
  public/locales/tr/common.json
  src/components/HashtagTimeline/index.tsx
  src/components/TweetWidget/index.tsx
  src/components/index.ts
  src/lib/getData/getHashtagPost.ts
  src/lib/getData/getHashtags.ts
  src/views/HashtagPostView/index.tsx
  types/hashtag.d.ts
  types/tweet.d.ts
Labels: enhancement
