Repository wsvvrijheid/samenvvv, pull requests merged in 2022-01, with the labels that each got.

#162 hided some links
  src/config/routes/index.ts
Labels: enhancement

#171 Hashtag Help Tour
  package.json
  pages/[...slug].tsx
  public/locales/en/common.json
  public/locales/nl/common.json
  public/locales/tr/common.json
  src/components/MentionList/index.tsx
  src/components/MentionSearch/index.tsx
  src/components/PostContainer/index.tsx
  src/components/StepsContent/index.tsx
  src/components/TrendListTabs/index.tsx
  src/components/index.ts
  src/utils/getSteps/index.ts
  src/utils/index.ts
  src/views/HashtagPostView/index.tsx
  yarn.lock
Labels: enhancement

#177 Permanent Hashtag Tab
  src/store/post-share.ts
  src/views/HashtagPostView/index.tsx
Labels: bug

#175 Remove Social Icons
  pages/index.tsx
  src/components/Card/index.tsx
  src/components/Slider/index.tsx
  src/components/SliderHero/index.tsx
  src/views/MainHashtagsView/index.tsx
  src/views/MainView/index.tsx
Labels: invalid, component

#176 Sort Blog Posts
  src/lib/getData/getBlogPosts.ts
Labels: bug

#179 Mention Modal Description
  src/components/MentionListItem/index.tsx
Labels: bug

#183 remove empty hashtag
  src/components/TagList/index.tsx
Labels: bug

#185 remove empty hashtag
  src/components/TagList/index.tsx
Labels: bug

#178 Random Post Content
  src/components/PostContainer/index.tsx
  src/utils/getRandomPostSentence/index.ts
  src/utils/index.ts
Labels: enhancement
